name: RJ_project_pipeline
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # may need to setup Node.js & Python3 on e.g. self-hosted
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: actions/checkout@v3
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install --upgrade pip
          pip install numpy
          pip install lap
          pip install -r requirements.txt
      - name: Build, tag, and push image
        run: |
          # Build a docker container
          echo "${{ secrets.DOCKERPWD }}" | docker login -u "tfq2830" --password-stdin
          docker build -t tfq2830/rj_project:v1.0.0 .
          docker push tfq2830/rj_project:v1.0.0
  Continuous-Deployment:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull latest images
        run: |
         docker pull tfq2830/rj_project:latest